"""形态数据字典（轻量模块，不依赖 backtrader/talib）。

从 signal_utils.py 拆分出来，供 web_app.py 等 Flask 请求处理场景使用，
避免 import backtrader 导致 Flask 主进程段错误。

signal_utils.py 仍保留向后兼容的 re-export，原有 `from signal_utils import ...` 不受影响。
"""

PATTERN_CN_NAMES = {
    'CDL2CROWS': '两只乌鸦',
    'CDL3BLACKCROWS': '三只乌鸦',
    'CDL3INSIDE': '三内部上涨',
    'CDL3LINESTRIKE': '三线打击',
    'CDL3OUTSIDE': '三外部上涨',
    'CDL3STARSINSOUTH': '南方三星',
    'CDL3WHITESOLDIERS': '三个白兵',
    'CDLABANDONEDBABY': '弃婴',
    'CDLADVANCEBLOCK': '大敌当前',
    'CDLBELTHOLD': '腰带线',
    'CDLBREAKAWAY': '脱离形态',
    'CDLCLOSINGMARUBOZU': '收盘缺影线',
    'CDLCONCEALBABYSWALL': '藏婴吞没',
    'CDLCOUNTERATTACK': '反击线',
    'CDLDARKCLOUDCOVER': '乌云盖顶',
    'CDLDOJI': '十字星',
    'CDLDOJISTAR': '十字星',
    'CDLDRAGONFLYDOJI': '蜻蜓十字',
    'CDLENGULFING': '吞没形态',
    'CDLEVENINGDOJISTAR': '黄昏十字星',
    'CDLEVENINGSTAR': '黄昏之星',
    'CDLGAPSIDESIDEWHITE': '跳空并列白线',
    'CDLGRAVESTONEDOJI': '墓碑十字',
    'CDLHAMMER': '锤子线',
    'CDLHANGINGMAN': '吊颈线',
    'CDLHARAMI': '孕线',
    'CDLHARAMICROSS': '十字孕线',
    'CDLHIGHWAVE': '风高浪大线',
    'CDLHIKKAKE': '陷阱形态',
    'CDLHIKKAKEMOD': '修正陷阱',
    'CDLHOMINGPIGEON': '家鸽形态',
    'CDLIDENTICAL3CROWS': '三胞胎乌鸦',
    'CDLINNECK': '颈内线',
    'CDLINVERTEDHAMMER': '倒锤子',
    'CDLKICKING': '反冲形态',
    'CDLKICKINGBYLENGTH': '反冲形态',
    'CDLLADDERBOTTOM': '梯形底部',
    'CDLLONGLEGGEDDOJI': '长脚十字',
    'CDLLONGLINE': '长蜡烛',
    'CDLMARUBOZU': '光头光脚',
    'CDLMATCHINGLOW': '相同低价',
    'CDLMATHOLD': '涨停形态',
    'CDLMORNINGDOJISTAR': '早晨十字星',
    'CDLMORNINGSTAR': '早晨之星',
    'CDLONNECK': '颈上线',
    'CDLPIERCING': '刺透形态',
    'CDLRICKSHAWMAN': '黄包车夫',
    'CDLRISEFALL3METHODS': '上涨/下跌三法',
    'CDLSEPARATINGLINES': '分手线',
    'CDLSHOOTINGSTAR': '射击之星',
    'CDLSHORTLINE': '短蜡烛',
    'CDLSPINNINGTOP': '纺锤线',
    'CDLSTALLEDPATTERN': '停顿形态',
    'CDLSTICKSANDWICH': '棒三明治',
    'CDLTAKURI': '探水竿',
    'CDLTASUKIGAP': '跳空缺口',
    'CDLTHRUSTING': '插入形态',
    'CDLTRISTAR': '三星形态',
    'CDLUNIQUE3RIVER': '奇特三川',
    'CDLUPSIDEGAP2CROWS': '上升缺口两乌鸦',
    'CDLXSIDEGAP3METHODS': '上升/下降跳空三法',
}

BUY_PATTERNS = [
    'CDL3INSIDE', 'CDL3OUTSIDE', 'CDLBELTHOLD', 'CDLCLOSINGMARUBOZU',
    'CDLCOUNTERATTACK', 'CDLDOJI', 'CDLDOJISTAR', 'CDLDRAGONFLYDOJI',
    'CDLENGULFING', 'CDLGAPSIDESIDEWHITE', 'CDLGRAVESTONEDOJI', 'CDLHAMMER',
    'CDLHARAMI', 'CDLHARAMICROSS', 'CDLHIGHWAVE', 'CDLHIKKAKE',
    'CDLHIKKAKEMOD', 'CDLHOMINGPIGEON', 'CDLINVERTEDHAMMER', 'CDLKICKING',
    'CDLKICKINGBYLENGTH', 'CDLLADDERBOTTOM', 'CDLLONGLEGGEDDOJI', 'CDLLONGLINE',
    'CDLMARUBOZU', 'CDLMATCHINGLOW', 'CDLMORNINGDOJISTAR', 'CDLMORNINGSTAR',
    'CDLPIERCING', 'CDLRICKSHAWMAN', 'CDLRISEFALL3METHODS', 'CDLSEPARATINGLINES',
    'CDLSHORTLINE', 'CDLSPINNINGTOP', 'CDLSTICKSANDWICH', 'CDLTAKURI',
    'CDLTASUKIGAP', 'CDLUNIQUE3RIVER', 'CDLXSIDEGAP3METHODS',
]

SELL_PATTERNS = [
    'CDL2CROWS', 'CDL3BLACKCROWS', 'CDL3LINESTRIKE', 'CDL3STARSINSOUTH',
    'CDL3WHITESOLDIERS', 'CDLABANDONEDBABY', 'CDLADVANCEBLOCK', 'CDLBREAKAWAY',
    'CDLCONCEALBABYSWALL', 'CDLDARKCLOUDCOVER', 'CDLEVENINGDOJISTAR',
    'CDLEVENINGSTAR', 'CDLHANGINGMAN', 'CDLIDENTICAL3CROWS', 'CDLINNECK',
    'CDLMATHOLD', 'CDLONNECK', 'CDLSHOOTINGSTAR', 'CDLSTALLEDPATTERN',
    'CDLTHRUSTING', 'CDLTRISTAR', 'CDLUPSIDEGAP2CROWS',
]

ALL_PATTERNS = sorted(set(BUY_PATTERNS + SELL_PATTERNS))

# 每个形态的样式说明（多空双向共用）
PATTERN_DESCRIPTIONS = {
    'CDL2CROWS': '两只乌鸦：三根蜡烛组合，第一根为上涨阳线，第二根为阴线且开盘高于第一根收盘（跳空高开）、收盘在前根实体内，第三根为阴线且开盘在第二根实体内（高于第二根收盘但低于第二根开盘）、收盘低于第二根收盘。出现在上升趋势顶部，预示见顶回落。',
    'CDL3BLACKCROWS': '三根连续下跌的阴线，每根开盘价都在前一根实体内，收盘价持续走低。出现在上升趋势后，预示强烈反转下跌。',
    'CDL3INSIDE': '孕线结构：第一根为长实体，第二根为短实体且完全包含在第一根实体内。上涨中预示反转下跌（看跌），下跌中预示反转上涨（看涨）。',
    'CDL3LINESTRIKE': '三线打击：延续形态（非反转）。三根同向蜡烛后第四根反向长蜡烛吞没前三根：三根阳线后长阴吞没为看涨延续（信号值+100），三根阴线后长阳吞没为看跌延续（信号值-100）。',
    'CDL3OUTSIDE': '吞没结构：第一根短实体被第二根长实体完全包含。上涨中看跌，下跌中看涨。',
    'CDL3STARSINSOUTH': '南方三星：三根逐渐走低的蜡烛，第一根为长阴线（可能有下影线），第二根较小的阴线（开盘低于第一根、实体在第一根下方），第三根为小实体且无下影线（光脚）。出现在下跌末端，预示底部反转上涨。',
    'CDL3WHITESOLDIERS': '三根连续上涨的阳线，每根收盘价都创新高，实体较长且基本无上影线。出现在下跌后或盘整中，预示强势上涨。',
    'CDLABANDONEDBABY': '三根蜡烛组合：第一根长实体，第二根十字星且跳空，第三根反向长实体且跳空。十字星与两根实体之间都有缺口。顶部看跌，底部看涨。',
    'CDLADVANCEBLOCK': '三根阳线，实体逐渐变短，上影线逐渐变长，预示上涨动能减弱，可能见顶回落。',
    'CDLBELTHOLD': '腰带线：单根长实体蜡烛。看涨腰带线（下跌中出现）：长阳线，开盘价等于最低价（无下影线），收盘端可有上影线；看跌腰带线（上涨中出现）：长阴线，开盘价等于最高价（无上影线），收盘端可有下影线。注意只有开盘端无影线，非光头光脚。',
    'CDLBREAKAWAY': '五根蜡烛组合，前四根延续原趋势，第五根跳空并反向突破。预示趋势反转。',
    'CDLCLOSINGMARUBOZU': '光头光脚收盘蜡烛：收盘价等于最高价（阳线）或最低价（阴线），另一端有短影线。',
    'CDLCONCEALBABYSWALL': '藏婴吞没：四根蜡烛组合，前两根为大阴线（第二根无下影线），第三根跳空高开但被吞没（小实体），第四根吞没第三根。出现在下跌末端，为看涨反转信号。',
    'CDLCOUNTERATTACK': '两根相反方向的长实体蜡烛，第二根收盘价与第一根收盘价相近。预示趋势可能反转。',
    'CDLDARKCLOUDCOVER': '两根蜡烛：第一根为上涨阳线，第二根开盘高于第一根最高价但收盘深入第一根实体内（超过中点）。看跌反转信号。',
    'CDLDOJI': '十字星：开盘价与收盘价相同或非常接近，实体极短。出现在趋势末端预示反转可能。',
    'CDLDOJISTAR': '十字星形态：第一根长实体后，第二根跳空形成十字星。预示趋势可能反转。',
    'CDLDRAGONFLYDOJI': '蜻蜓十字：开盘价、收盘价、最高价相同，有长下影线。出现在下跌底部为看涨反转。',
    'CDLENGULFING': '吞没形态：第二根实体完全吞没第一根实体。上涨中看跌，下跌中看涨。',
    'CDLEVENINGDOJISTAR': '三根蜡烛：第一根长阳线，第二根跳空十字星，第三根长阴线深入第一根实体。看跌反转信号。',
    'CDLEVENINGSTAR': '三根蜡烛：第一根长阳线，第二根小实体跳空上涨，第三根长阴线深入第一根实体。看跌反转信号。',
    'CDLGAPSIDESIDEWHITE': '两根并列白线：第二根跳空开盘且与第一根实体大小相近，均为阳线。看涨延续信号。',
    'CDLGRAVESTONEDOJI': '墓碑十字：开盘价、收盘价、最低价相同，有长上影线。出现在上涨顶部为看跌反转。',
    'CDLHAMMER': '锤子线：实体较小，下影线为实体的2倍以上，几乎无上影线。出现在下跌底部为看涨反转。',
    'CDLHANGINGMAN': '吊颈线：形态同锤子线，但出现在上涨顶部，为看跌反转信号。',
    'CDLHARAMI': '孕线：第一根长实体包含第二根短实体。预示趋势可能反转。',
    'CDLHARAMICROSS': '十字孕线：第一根长实体，第二根为十字星且被第一根包含。反转信号更强。',
    'CDLHIGHWAVE': '风高浪大线：实体较短，上下影线都很长。预示趋势不确定，可能反转。',
    'CDLHIKKAKE': '陷阱形态：先形成孕线，随后价格未延续而反向突破孕线高低点。预示原趋势失败。',
    'CDLHIKKAKEMOD': '修正陷阱：与陷阱形态类似，区别在于第三根的突破伴随跳空缺口（而非普通突破）。',
    'CDLHOMINGPIGEON': '家鸽形态：两根阴线，第一根长实体包含第二根短实体。出现在下跌中为看涨反转。',
    'CDLIDENTICAL3CROWS': '三胞胎乌鸦：三根连续阴线，开盘价和收盘价分别相近，实体大致相同。看跌反转信号。',
    'CDLINNECK': '颈内线：第一根长阴线，第二根小阳线开盘低于第一根最低价，收盘在前根实体内但接近最低价。看跌延续。',
    'CDLINVERTEDHAMMER': '倒锤子：实体较小，上影线为实体的2倍以上，几乎无下影线。出现在下跌底部为看涨反转。',
    'CDLKICKING': '反冲形态：两根相反颜色的长实体蜡烛（一阴一阳），之间有跳空缺口。看涨反冲：阴线后阳线跳空高开；看跌反冲：阳线后阴线跳空低开。',
    'CDLKICKINGBYLENGTH': '反冲形态（按长度）：与反冲形态类似，但两根蜡烛长度有差异。',
    'CDLLADDERBOTTOM': '梯形底部：五根蜡烛组合，前三根为下跌阴线且开盘价逐步走低，第四根为带长上影线的蜡烛，第五根为阳线突破。看涨反转。',
    'CDLLONGLEGGEDDOJI': '长脚十字：十字星形态，但上下影线都很长。预示趋势不确定，可能反转。',
    'CDLLONGLINE': '长蜡烛：实体较长，预示当前趋势强劲。',
    'CDLMARUBOZU': '光头光脚：无上下影线或极短，实体占据整根蜡烛。',
    'CDLMATCHINGLOW': '相同低价：两根阴线，收盘价相同或相近。出现在下跌底部为看涨反转。',
    'CDLMATHOLD': '涨停形态：上涨中回调后再次突破前高。看涨延续。',
    'CDLMORNINGDOJISTAR': '三根蜡烛：第一根长阴线，第二根跳空十字星，第三根长阳线深入第一根实体。看涨反转。',
    'CDLMORNINGSTAR': '三根蜡烛：第一根长阴线，第二根小实体跳空下跌，第三根长阳线深入第一根实体。看涨反转。',
    'CDLONNECK': '颈上线：第一根长阴线，第二根小阳线开盘低于第一根最低价，收盘接近第一根最低价。看跌延续。',
    'CDLPIERCING': '刺透形态：第一根长阴线，第二根开盘低于第一根最低价但收盘深入第一根实体上半部分。看涨反转。',
    'CDLRICKSHAWMAN': '黄包车夫：十字星形态，上下影线较长且对称。预示趋势不确定。',
    'CDLRISEFALL3METHODS': '上涨三法：五根蜡烛，第一根长阳线，中间三根小阴线回撤，第五根长阳线创新高。看涨延续。',
    'CDLSEPARATINGLINES': '分手线：两根相反方向的蜡烛，但开盘价相同。上涨中第二根为阳线为看涨延续。',
    'CDLSHOOTINGSTAR': '射击之星：实体较小，上影线为实体的2倍以上，几乎无下影线。出现在上涨顶部为看跌反转。',
    'CDLSHORTLINE': '短蜡烛：实体较短，预示当前趋势可能减弱。',
    'CDLSPINNINGTOP': '纺锤线：实体较短，上下影线都较长。预示多空平衡，可能反转。',
    'CDLSTALLEDPATTERN': '停顿形态：两根阳线后第三根小实体蜡烛，预示上涨动能减弱。',
    'CDLSTICKSANDWICH': '棒三明治：两根长阴线中间夹一根阳线，两根阴线收盘价相近。看涨反转。',
    'CDLTAKURI': '探水竿：形态同锤子线，但下影线极长（实体的3倍以上）。看涨反转信号更强。',
    'CDLTASUKIGAP': '跳空缺口：上涨中跳空后的小实体蜡烛，预示趋势延续。',
    'CDLTHRUSTING': '插入形态：第一根长阴线，第二根小阳线开盘低于第一根最低价，收盘在前根实体内但未超过中点。看跌延续。',
    'CDLTRISTAR': '三星形态：三根十字星组合。顶部看跌，底部看涨。',
    'CDLUNIQUE3RIVER': '奇特三川：三根蜡烛，第一根长阴线，第二根小阴线创新低，第三根小阳线收盘低于第二根。看涨反转。',
    'CDLUPSIDEGAP2CROWS': '上升缺口两乌鸦：第一根阳线，后两根阴线，第二根跳空高开，第三根吞没第二根。看跌反转。',
    'CDLXSIDEGAP3METHODS': '上升/下降跳空三法：跳空缺口后的回填补缺。看涨延续或看跌延续。',
}


def get_pattern_description(name):
    """获取形态的中文说明"""
    return PATTERN_DESCRIPTIONS.get(name, '暂无说明')
